site_name: Natal

site_url: https://hoishing.github.io/natal
repo_url: https://github.com/hoishing/natal
extra_css:
    - stylesheets/extra.css

theme:
    font:
        text: Varela Round
    name: "material"
    icon:
        repo: fontawesome/brands/github
    favicon: assets/favicon.png
    logo: assets/natal-logo.svg
    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: black
          scheme: slate
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: white
          scheme: default
          toggle:
              icon: material/toggle-switch
              name: Switch to system preference

        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/link
              name: Switch to dark mode

    features:
        - navigation.instant
        - navigation.tracking
        # - navigation.sections
        - navigation.expand
        # - toc.integrate

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/hoishing
        - icon: fontawesome/brands/x-twitter
          link: https://x.com/hoishing
        - icon: fontawesome/brands/github
          link: https://github.com/hoishing
        - icon: fontawesome/brands/dev
          link: https://dev.to/hoishing

plugins:
    - social
    - search:
          lang: en
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  options:
                      show_root_heading: true
                      show_signature_annotations: true
                      members_order: alphabetical

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets

nav:
    - Quick Start: index.md
    - References:
          - Chart: chart.md
          - Classes: classes.md
          - Config: config.md
          - Constants: const.md
          - Data: data.md
          - Stats: stats.md
          - Utils: utils.md
    - License: license.md
    - Author: https://hoishing.github.io
